apiVersion: v1
kind: Namespace
metadata:
  name: shieldops
  labels:
    name: shieldops
---
apiVersion: v1
kind: Secret
metadata:
  name: shieldops-secrets
  namespace: shieldops
type: Opaque
stringData:
  JWT_SECRET: "shieldops-super-secret-jwt-key-CHANGE-IN-PRODUCTION"
  JWT_REFRESH_SECRET: "shieldops-refresh-secret-CHANGE-IN-PRODUCTION"
  INTERNAL_API_KEY: "internal-secret-key-CHANGE-IN-PRODUCTION"
  MONGO_ROOT_USER: "admin"
  MONGO_ROOT_PASS: "shieldops_pass_CHANGE_IN_PRODUCTION"
  MONGO_URI_AUTH: "mongodb://admin:shieldops_pass@mongo-service:27017/shieldops-auth?authSource=admin"
  MONGO_URI_USERS: "mongodb://admin:shieldops_pass@mongo-service:27017/shieldops-users?authSource=admin"
  MONGO_URI_DATA: "mongodb://admin:shieldops_pass@mongo-service:27017/shieldops-data?authSource=admin"
